# Generated by Django 4.2 on 2026-05-01 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, default='Portfolio Contact', max_length=300)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, help_text='Mark as read in admin')),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project title', max_length=200)),
                ('description', models.TextField(help_text='Detailed project description')),
                ('short_description', models.CharField(blank=True, help_text='Short summary shown on project cards', max_length=300)),
                ('tech_stack', models.CharField(help_text="Comma-separated tech stack (e.g. 'Python, Django, PostgreSQL')", max_length=500)),
                ('image', models.ImageField(blank=True, help_text='Project screenshot or thumbnail', null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository link', null=True)),
                ('live_url', models.URLField(blank=True, help_text='Live demo / deployed URL', null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Featured projects appear on the Home page')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
